version: 1
services:
  rails-app:
    image: '{DOCKER_USERNAME}/datadog-rails-prototype:dev'
    ports:
      - '3000:3000'
    environment:
      - DD_AGEN_HOST=datadog
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ENV=rails-prototype
      - DD_SERVICE=fullstack-app
      - DD_SITE=datadoghq.com
      - DD_VERSION
      - DD_USERNAME
      - DD_PASSWORD
      - DD_CLIENT_TOKEN
      - DD_APPLCIATION_ID
    labels:
      com.datadoghq.ad.logs: '[{"source": "ruby", "service":"fullstack-app"}]'
      com.datadoghq.tags.env: 'rails-prototype'
      com.datadoghq.version: '2.2.0'
      my.custom.label.team: 'fullstack'
  datadog:
    image: 'datadog/agent:7.41.1'
    environment:
      - DD_API_KEY
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_DOCKER_LABELS_AS_TAGS={"my.custom.lable.team":"fullstack"}
      - DDD_TAGS='env:rails-prototype'
      - DD_HOSTNAME=my-prototype-host
      - DD_APM_NON_LOCAL_TRAFFIC=true
    ports:
      - 127.0.0.1:8126:8126/tcp

    